In [12]:
# Reshape
import numpy as np 
# reshape 1d array to 3x4 array
arr=np.arange(0,12)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arr=arr.reshape(3,4)

In [15]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
# -1 will arrange the dimentions automatically
arr.reshape(6,-12)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
arr.reshape(12,-1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

### flat, flatten

In [20]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
ar=arr.flat[:]

In [22]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr.flat[5]

5

In [25]:
np.array([[23,24],[7678,56]])

array([[  23,   24],
       [7678,   56]])

In [26]:
np.array([[23,24],[7678,56]]).flat[:]

array([  23,   24, 7678,   56])

In [27]:
# flatten
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr.flatten() #row

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
arr.flatten(order='F') # Column

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [30]:
arr.flatten(order='C') #row

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
# T gives Transpose
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [32]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
# Stacking 

# Stack
This function joins the sequence of array along a new axis.

In [34]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [35]:
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [36]:
# axis=0
np.stack((arr1,arr2),0).shape

(2, 2, 2)

In [37]:
# axis=1
np.stack((arr1,arr2),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [38]:
# vstack
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [40]:
# Concatenation 
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [42]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [44]:
# split

In [45]:
a=np.arange(9)

In [46]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [48]:
np.split(a,[4,8])

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([8])]

In [49]:
#split
a=np.arange(16).reshape(4,4)

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [53]:
# unique
a=np.array([1,2,3,44,3,2,44])

In [54]:
np.unique(a)

array([ 1,  2,  3, 44])

# Maths operations

In [55]:
a=np.arange(0,20,2)

In [56]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
np.sin(a)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [58]:
np.cos(a)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671])

In [59]:
np.exp(a)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [60]:
np.log(a)

/tmp/ipykernel_23799/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176])

In [61]:
np.arctan(a)

array([0.        , 1.10714872, 1.32581766, 1.40564765, 1.44644133,
       1.47112767, 1.48765509, 1.49948886, 1.50837752, 1.51529782])

In [62]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
a_list=[x/(x+1) for x in a]

In [64]:
a_list

[0.0,
 0.6666666666666666,
 0.8,
 0.8571428571428571,
 0.8888888888888888,
 0.9090909090909091,
 0.9230769230769231,
 0.9333333333333333,
 0.9411764705882353,
 0.9473684210526315]

In [65]:
f=np.vectorize(lambda x:x/(x+1))

In [66]:
f(a)

array([0.        , 0.66666667, 0.8       , 0.85714286, 0.88888889,
       0.90909091, 0.92307692, 0.93333333, 0.94117647, 0.94736842])

In [67]:
# Linear Algebra

In [68]:
# Inverse matrix np.linalg.inv
# Determinant of  matrix np.linalg.det
# EigenValue np.linalg.eig

In [93]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,17).reshape(4,4)


In [94]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
B=np.reshape(b,(-1,2))

In [96]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [97]:
B

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [100]:
np.linalg.inv(b)

array([[ 3.94064967e+15, -4.50359963e+15, -2.81474977e+15,
         3.37769972e+15],
       [-4.12829966e+15,  4.50359963e+15,  3.37769972e+15,
        -3.75299969e+15],
       [-3.56534971e+15,  4.50359963e+15,  1.68884986e+15,
        -2.62709978e+15],
       [ 3.75299969e+15, -4.50359963e+15, -2.25179981e+15,
         3.00239975e+15]])

In [74]:
x= np.array([[1,2],[3,4]])


In [75]:
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [76]:
np.linalg.det(x)

-2.0000000000000004

In [77]:
np.linalg.eig(x)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [78]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
np.dot(a,b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

In [81]:
# User Defined Function 


In [82]:
def fun1(k):
    return k**2

In [83]:
arr=np.array([[12,45,45],[12,88,63]])

In [84]:
fun1(arr)

array([[ 144, 2025, 2025],
       [ 144, 7744, 3969]])